# -*- coding: utf-8 -*-
"""Trabajo clase

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n5LIhZ-pwjOUMu1m3VAFhB79m9euncej
"""

A=int(input("Ingrese el valor de A: "))
B=int(input("Ingrese el valor de B: "))

if A>B:
  print("A es mayor que B")

elif A<B:
  print("A es menor que B")

else:
    print("A es igual a B")

nota_1=2.5*0.3
nota_2=3*0.15
nota_3=4.5*0.15
nota_4=5.0*0.2
nota_5=4.7*0.2

prom = nota_1+nota_2+nota_3+nota_4+nota_5/5
if prom>=3:
  print("aprobado")
  print(prom)

Y=int(input(" Ingrese el valor de Y:"))
Z=int(input("Ingrese el valor de Z:"))

if Y>Z:
  print("X=1")

elif Y<Z:
  print("X=3")

else:
  print("Y=Z")

A=int(input("Ingrese el valor de A:"))
B=int(input("Ingrese el valor de B:"))
C=int(input("Ingrese el valor de C:"))

if A>B>C:
   print(A,B,C)

elif A>C>B:
  print(A,C,B)

elif B>A>C:
  print(B,A,C)

elif B>C>A:
  print(B,C,A)

elif C>A>B:
  print(C,A,B)

elif C>B>A:
  print(C,B,A) #AAAAAAAAAAAAAAAAAAAAAAAAAAAA CASI NO ME SALEEEEE :)

else:
  print(A,B,C) #por si los valores son iguales, me falta cuando dos valores son iguales

A>C

INSCRIPCION=int(input("Ingrese su número de inscripción:"))
NOMBRE=(input("Ingrese su nombre completo:"))
PATRIMONIO=float(input("Ingrese su patrimonio:"))
ESTRATO=int(input("Ingrese su estrato socioeconómico:"))

if PATRIMONIO>2000000 and ESTRATO>3:
  print("Su valor a pagar es: ")
  print(PATRIMONIO*0.3)

elif PATRIMONIO>2000000 and ESTRATO <=3:
  print("Su valor a pagar es: 50.000")

elif PATRIMONIO<=2000000 and ESTRATO>3:
  print("Su valor a pagar es: 50.000")

elif PATRIMONIO<=2000000 and ESTRATO<=3:
  print("Su valor a pagar es: 50.000") #No sé si interpreté bien el enunciado

M1=int(input("Ingrese la masa de la esfera 1:"))
V1=int(input("Ingrese el volumen de la esfera 1:"))
M2=int(input("Ingrese la masa de la esfera 2:"))
V2=int(input("Ingrese el volumen de la esfera 2:"))
M3=int(input("Ingrese la masa de la esfera 3:"))
V3=int(input("Ingrese el volumen de la esfera 3:"))

D1=(M1//V1)
D2=(M2//V2)
D3=(M3//V3)

if D1>D2 and D1>D3:
  print(D1, "La esfera de mayor densidad es la 1")

elif D2>D1 and D2>D3:
  print(D2, "La esfera de mayor densidad es la 2")

elif D3>D1 and D3>D2:
  print(D3, "La esfera de mayor densidad es la 3")

elif D1==D2 and D1>D3:
  print(D1, "La esfera de mayor densidad es la 1")

elif D1==D2 and D2>D3:
  print(D2, "La esfera de mayor densidad es la 2")

elif D1==D3 and D1>D2:
  print(D1,"La esfera de mayor densidad es la 1")

elif D1==D3 and D3>D2:
  print(D2, "La esfera de mayor densidad es la 3")

elif D2==D3 and D2>D1:
  print(D2, "La esfera de mayor densidad es la 2")

elif D2==D3 and D3>D1:
  print(D3, "La esfera de mayor densidad es la 3")

else:
  print("Las tres esferas tienen igual densidad")

A=int(input("Ingrese el dato 1:"))
B=int(input("Ingrese el dato 2:"))
C=int (input("Ingrese el dato 3:"))
D=int(input("Ingrese el dato 4:"))