# -*- coding: utf-8 -*-
"""Trabajo clase

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n5LIhZ-pwjOUMu1m3VAFhB79m9euncej
"""

A=9
B=9
print("if A><=B")

nota_1=2.5*0.3
nota_2=3*0.15
nota_3=4.5*0.15
nota_4=5.0*0.2
nota_5=4.7*0.2

prom = nota_1+nota_2+nota_3+nota_4+nota_5/5
if prom>=3:
  print("aprobado")
  print(prom)

int(input("Y:"))
int(input("Z:"))

if Y>Z:
  X=1

  if Y==Z:
    X=2

if Y<Z:
  X=3



