# -*- coding: utf-8 -*-
"""Trabajo clase 2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1h4FtRCbxPr8XQawWXFfMHVMX6BKr7iTh
"""

A=int(input("Ingrese el primer digito:"))
B=int(input("Ingrese el segundo digito:"))
ACUMULADOR=0

while True:
  ACUMULADOR+=A
  B-=1

  if B==0:  #Asegurarse de que el condicional if y break estén dentro del ciclo.
    print(ACUMULADOR)
    break

acum_notas=0
num_notas=0

while True:
  nota=float(input("Ingrese una nota  entre 0 y 5, o ingrese -1 para terminar: "))
  if nota==-1:
    break

  if nota<0 or nota>5:
    print("ERROR, ingrese una nota valida (0-5)")
    continue
  acum_notas+=nota
  num_notas+=1

promedio=acum_notas//num_notas
print("El promedio de notas es:", promedio)

cont=0
acum=1

while True:
  n=int(input("Ingrese el valor de n. entre (0-9)"))
  x=int(input("Ingrese el valor de x. entre (0-9)"))

  if 0<=n <=9 and 0<=x <=9:
    break
  else:
    print("ERROR, ingrese valores entre 0 y 9")

while cont<=n:
  resultado=acum
  print(f"{x}**{cont}={resultado}")

  cont+=1
  acum*=x

#Hacer un algoritmo que encuentre la suma de los números impares comprendidos entre 1 y N.

n=int(input("Ingrese un numero entero entre 1 y N: "))
i=1
sum=0

while i<=n:
  if i%2!=0:
    sum+=i
  i+=1

print("La suma entre 1 y", n, "es:", sum)

